name: build-test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build-job:  # Dockerfileをビルドする
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: docker build -t action-sample .

  test-job:   # コンテナを起動してテストする
    needs: build-job
    steps:
      - name: Run test script
        shell: bash
        run: docker run action-sample2

