name: build-test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build-job:  # Dockerfileをビルドする
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: docker build -t action-sample .
      - name: Run container
        uses: docker://action-sample:latest
      
      # - name: save image to file
      #   run: docker save action-sample > action-sample.tar
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: action-sample
      #     path: action-sample.tar
      #     retention-days: 5

  # test-job:   # コンテナを起動してテストする
  #   runs-on: ubuntu-latest
  #   needs: build-job
  #   steps:
  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: action-sample
  #     - name: load image from file
  #       run: docker load --input action-sample.tar
  #     - name: Run test script
  #       shell: bash
  #       run: docker run action-sample

